### ISSUE TITLE
Conflict with https://github.com/stefankoegl/python-json-patch

### ISSUE THREAD

**Issue by yan12125** [xlwings/jsondiff#24]
Both Python packages installs an executable `jsondiff`. As a reulst it's impossible to install both python-jsondiff and python-jsonpatch on Arch Linux https://bugs.archlinux.org/task/60911.

**Comment by yan12125** [comment]
@fzumstein Apparently jsonpatch is more popular than jsondiff - more packages depend on the former [1][2]. How do you think about using a new name for the script and deprecating the current one?

[1] https://libraries.io/pypi/jsonpatch
[2] https://libraries.io/pypi/jsondiff

**Comment by fzumstein** [comment]
What would be your suggestion?

**Comment by yan12125** [comment]
How about `jsondiff-cli`?

**Comment by fzumstein** [comment]
to be clear, this is only about the CLI and not the name of the python package, correct? In that case we could rename the cli into something like `jdiff` or `jd`. `jsondiff-cli` seems way to verbose.

**Comment by yan12125** [comment]
> to be clear, this is only about the CLI and not the name of the python package, correct?

yes!

> In that case we could rename the cli into something like jdiff or jd. jsondiff-cli seems way to verbose.

Either sounds better than my long proposal. Though I guess jd might be too short and bring another conflict.

**Comment by yan12125** [comment]
@fzumstein: I created #26 to deprecate the jsondiff command in favor of jdiff. Could you have a look?

**Comment by fzumstein** [comment]
released as 1.2.0
