### ISSUE TITLE
Is there a way to use indent other than the CLI tool?

### ISSUE THREAD

**Issue by sohamdshah** [xlwings/jsondiff#29]
Currently I use the following:

with open('a.json', encoding='utf-8') as f1:
    data1 = json.loads(f1.read())
with open('b.json', encoding='utf-8') as f2:
    data2 = json.loads(f2.read())

abc=diff(data1, data2, syntax='symmetric')
print(json.dumps(abc, indent=4))

**Comment by mic-max** [comment]
Not currently, `json.dumps` is also how the `cli.py` does it

**Comment by johannes-michael** [comment]
`json.dumps` works fine, or use the provided `JsonDumper`. Just be sure to include `marshal=True` in your `diff`:

```
data_diff = diff(d1, d2, marshal=True, syntax="explicit")

print(json.dumps(data_diff, indent=2))

dumper = JsonDumper(indent=2)
print(JsonDumper(data_diff))
```

**Comment by corytodd** [comment]
Closing as answered.
