### ISSUE TITLE
Publish sdist and bdist wheel

### ISSUE THREAD

**Issue by groodt** [xlwings/jsondiff#30]
The benefits of wheels are well documented. See: https://pythonwheels.com/
This package is pure Python and publishing it as both source and as a wheel is simple.

Would you accept a PR that adds a Makefile that makes it easy for you to release both an sdist and bdist_wheel to PyPI when you create releases?

**Comment by fzumstein** [comment]
sure

**Comment by fzumstein** [comment]
actually, I take this back, not a makefile please but GitHub Actions.

**Comment by corytodd** [comment]
I think both sdist and bdist are now published:

https://pypi.org/project/jsondiff/#files
