### ISSUE TITLE
No difference label if one of JSON is empty

### ISSUE THREAD

**Issue by tatulea** [xlwings/jsondiff#36]
Hi,

I did some tests with the library and I have a case scenario where one of the compared JSON is empty: { }. I am using syntax='explicit' and the diff returns me exactly the JSON that is not the one empty. My problem is that I would like it to return me something like:

```js
{
  insert: ...
}
```

The "insert" tag is quite important during my parsing.

**Comment by tafli** [comment]
Same here. l got an empty JSON array and need to know it an element is inserted.

As an example I have following snippet:
```python
from jsondiff import diff
diff([], [{'a'}])
>>> [{'a'}]
```

Expected is following:
```python
diff([], [{'a'}])
>>> {insert: [(0, {'a': True})]}
```

Am I missing an option to this or is this a bug?

**Comment by 0xquad** [comment]
For arrays, my workaround is to force at least one element in each of them. Prepending an element will offset all positions by +1, but appending the element won't change the indices.

```python
>>> jsondiff.diff( [], [{'a': True}] )    # bug
[{'a': True}]
>>> jsondiff.diff( [{'a': True}], [] )    # bug
[]
>>> jsondiff.diff( [...] + [], [...] + [{'a': True}] )
{insert: [(1, {'a'})]}
>>> jsondiff.diff( [...] + [{'a': True}], [...] + [] )
{delete: [1]}
>>> jsondiff.diff( [0], [123], syntax='explicit' )    # bug
[123]
>>> jsondiff.diff( ['x'] + [...], [123] + [...], syntax='explicit' )
{insert: [(0, 123)], delete: [0]}
```

The `...` is the actual `Ellipsis` literal instance, but almost any value could be used.

Not sure if it works for nested structures.

However it doesn't seem to fix the following weird boolean evaluation cases. Beware of these if your objects contain boolean values.

```python
>>> jsondiff.diff( [True], [1], syntax='explicit' )
{}
>>> jsondiff.diff( [False], [0], syntax='explicit' )
{}
>>> jsondiff.diff( [True, True], [1, 1], syntax='explicit')    # even with multiple values
{}
>>> jsondiff.diff( [True, True], [1, 2], syntax='explicit')    # but this works (2 != True)
{insert: [(1, 2)], delete: [0]}
>>> jsondiff.diff( [...] + [False], [...] + [0], syntax='explicit' )    # try the workaround; no go
{}
```

For dictionaries, there are more than one workarounds, but it gives different results:

```python
>>> jsondiff.diff( {'a': 123}, {'b': 321}, syntax='explicit' )
{'b': 321}
>>> jsondiff.diff( {'a': 123, 'x': 99}, {'b': 321, 'x': 99}, syntax='explicit' )   # adding a dict element fixes it
{insert: {'b': 321}, delete: ['a']}
>>> jsondiff.diff( {'x': {'a': 123}}, {'x': {'b': 321}}, syntax='explicit' )    # encapsulating in an outer dictionary
{update: {'x': {'b': 321}}}
```
