### ISSUE TITLE
Difference between jsondiff and json-diff?

### ISSUE THREAD

**Issue by tommycarstensen** [xlwings/jsondiff#50]
Can you add to the README what is the difference between jsondiff and json-diff? Thanks 🙂

https://pypi.org/project/json-diff/

**Comment by Cajuteq** [comment]
The two packages don't have the same maintainer, jsondiff is more widely used and is more generic. At the time of writing, jsondiff has 258 dependent repositories and 622 stars, while json-diff has 0 dependent repositories and 7 stars.

Developers tend to favor more widely used software that are less prone to errors, breaking changes, more reviewed, and so more safe, secure and stable across time.

Disclaimer : I don't use code or maintain any of the aforementioned repositories

**Comment by corytodd** [comment]
Closed because I believe the question was answered above. Feel free to open if you disagree.
