### ISSUE TITLE
Equality operator implementation for Symbols

### ISSUE THREAD

**Issue by GregoirePelegrin** [xlwings/jsondiff#54]
When the diff has been performed, we obtain a dictionary with keys of type `Union[T|jsondiff.symbols.Symbol]` (`T` being the initial type(s) of the keys in the initial two dictionaries). This led me to have troubles comparing efficiently the keys, especially because the `jsondiff.symbols.Symbol` class does not instantiate any king of comparison operators.
It would be way easier to have a simple equality operator returning `True` if the `label` attributes of the two `Symbol`s are identical.

**Comment by corytodd** [comment]
I believe this is fixed by #55
