### ISSUE TITLE
When giving a file that is not JSON, there's traceback output

### ISSUE THREAD

**Issue by doctordesh** [xlwings/jsondiff#71]
Hi, thanks for a good tool. I like it! 

However, this happens from time to time, that I use it with a file that is not a JSON. This is caused by a typo or other human error. 

```
> jdiff file-a.json file-b.json 
Traceback (most recent call last):
  File "/opt/conda/bin/jdiff", line 8, in <module>
   ...
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I think that the end user should never have to see a traceback. Wrapping this call into a `try-except` block to just output that `file-a.json` is not a valid JSON file is a resonable quality-of-life improvement. I'm a developer and understand the traceback, but someone who is not as technically savvy will not necessarily understand the quite cryptic JSONDecodeError message. 

All the best

**Comment by corytodd** [comment]
I think this is a reasonable request. How does https://github.com/xlwings/jsondiff/pull/72 look to you?

The API surface is a bit awkward to not break but this should be sufficient.

**Comment by doctordesh** [comment]
#72 looks good!

**Comment by fzumstein** [comment]
Hey @corytodd thanks! Would you be up for becoming an official maintainer of jsondiff?

**Comment by corytodd** [comment]
Absolutely @fzumstein, happy to help :)
