### ISSUE TITLE
New release??

### ISSUE THREAD

**Issue by cavanaug** [xlwings/jsondiff#75]
Can you perform a new release so folks can pipx install this....

**Comment by a-detiste** [comment]
Please tag a new release to allow python3-nose-random removal from our distro. Greetings

**Comment by corytodd** [comment]
@fzumstein what can I do to help get this released?

**Comment by fzumstein** [comment]
@corytodd do you feel like adding a GH actions pipeline for packaging?

**Comment by corytodd** [comment]
Sure I can do that. Do you want me to store the build here on GitHub?

**Comment by fzumstein** [comment]
I can add the credentials to upload it to pypi. There's a pre-made publish python package here: https://github.com/xlwings/jsondiff/actions/new

How are the cool kids handling the version string these days? I used to do something like this: https://github.com/hhas/appscript/blob/master/.github/workflows/main.yml#L32-L38 but not sure if that's considered best practice.

**Comment by corytodd** [comment]
> I can add the credentials to upload it to pypi. There's a pre-made publish python package here: https://github.com/xlwings/jsondiff/actions/new
👍 

> How are the cool kids handling the version string these days? I used to do something like this: https://github.com/hhas/appscript/blob/master/.github/workflows/main.yml#L32-L38 but not sure if that's considered best practice.
I'm not sure 😀 
I might try something like https://github.com/pypa/setuptools_scm so we can use tags and not have to manually twiddle a version string in source.
