### ISSUE TITLE
docs: what do the different syntax options actually DO?

### ISSUE THREAD

**Issue by howardjones** [xlwings/jsondiff#76]
Syntax can be compact,symmetric,explicit,rightonly according to the README, but it doesn't mention what those mean. In fact, there isn't even a docstring in the code for what the differences are...

**Comment by payam54** [comment]
I agree. Having some small docstrings would be a huge help, if not updating the README.

**Comment by corytodd** [comment]
Addressed by #79. Thanks for your help @payam54 !
